insert into category_name (id, category_name) values (1, 'Awaiting court outcome');
insert into category_name (id, category_name) values (2, 'Court result unavailable');
insert into category_name (id, category_name) values (3, 'Court case unable to proceed');
insert into category_name (id, category_name) values (4, 'Local resolution');
insert into category_name (id, category_name) values (5, 'Investigation complete; no suspect identified');
insert into category_name (id, category_name) values (6, 'Offender deprived of property');
insert into category_name (id, category_name) values (7, 'Offender fined');
insert into category_name (id, category_name) values (8, 'Offender given absolute discharge');
insert into category_name (id, category_name) values (9, 'Offender given a caution');
insert into category_name (id, category_name) values (10, 'Offender given a drugs possession warning');
insert into category_name (id, category_name) values (11, 'Offender given a penalty notice');
insert into category_name (id, category_name) values (12, 'Offender given community sentence');
insert into category_name (id, category_name) values (13, 'Offender given conditional discharge');
insert into category_name (id, category_name) values (14, 'Offender given suspended prison sentence');
insert into category_name (id, category_name) values (15, 'Offender sent to prison');
insert into category_name (id, category_name) values (16, 'Offender otherwise dealt with');
insert into category_name (id, category_name) values (17, 'Offender ordered to pay compensation');
insert into category_name (id, category_name) values (18, 'Suspect charged as part of another case');
insert into category_name (id, category_name) values (19, 'Suspect charged');
insert into category_name (id, category_name) values (20, 'Defendant found not guilty');
insert into category_name (id, category_name) values (21, 'Defendant sent to Crown Court');
insert into category_name (id, category_name) values (22, 'Unable to prosecute suspect');
insert into category_name (id, category_name) values (23, 'Formal action is not in the public interest');
insert into category_name (id, category_name) values (24, 'Action to be taken by another organisation');
insert into category_name (id, category_name) values (25, 'Further investigation is not in the public interest');
insert into category_name (id, category_name) values (26, 'Further action is not in the public interest');
insert into category_name (id, category_name) values (27, 'Under investigation');
insert into category_name (id, category_name) values (28, 'Status update unavailable');